import Head from 'next/head'
import React from 'react';
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import { useContext, useEffect } from 'react'
import { PostContext } from '@/context/PostContext'
import { AccountContext } from '@/context/AccountContext'
import LeftSideBar from '@/components/LeftSideBar';
import RightSidebar from '@/components/RightSideBar';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const { postContractCABI, postContractCAddress, setPostcContract, postcContract, postContractABI, postContractAddress, setPostContract, postContract } = useContext(PostContext)
  const { followContractAddress, followContractABI, userInter, setUserInter, web3, user, address } = useContext(AccountContext)
  console.log(user)
  // useEffect(() => {
  //   if (!postcContract) {
  //     const PostcContract = new web3.eth.Contract(postContractCABI, postContractCAddress);
  //     setPostcContract(PostcContract)
  //   }
  //   if (!postContract) {
  //     const PostContract = new web3.eth.Contract(postContractABI, postContractAddress);
  //     setPostContract(PostContract)
  //   }
  //   if (!userInter) {
  //     const UserInterContract = new web3.eth.Contract(followContractABI, followContractAddress);
  //     setUserInter(UserInterContract)
  //   }
  // }, [])
  useEffect(() => {
    if (web3) { // Add this check
      if (!postcContract) {
        const PostcContract = new web3.eth.Contract(postContractCABI, postContractCAddress);
        setPostcContract(PostcContract);
      }
      if (!postContract) {
        const PostContract = new web3.eth.Contract(postContractABI, postContractAddress);
        setPostContract(PostContract);
      }
      if (!userInter) {
        const UserInterContract = new web3.eth.Contract(followContractABI, followContractAddress);
        setUserInter(UserInterContract);
      }
    } else {
      console.error("Web3 is not initialized");
    }
  }, [web3]); // Ensure it runs when web3 changes
  
  return (
    <>
      <Head>
        <title>Turtle</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
      <div className='relative'>
        <LeftSideBar profile={user} />
        <div className='absolute p-4 inset-y-0 right-36'>
          <div class="post-box bg-white p-2  rounded-md">
            <img src="data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxMSEhUTExMWFhUXFxsaGBgYGR0WIBcgGyMaIR8dHR8eICggGh8lIB8eIjIhJSkxLi4vHR8zODMtNygtLisBCgoKDg0OGxAQGy0lICYtLS0tLS0tLS0tLy0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLf/AABEIAQ0AuwMBIgACEQEDEQH/xAAcAAACAwEBAQEAAAAAAAAAAAAGBwAEBQMIAgH/xABNEAACAQIEAwUDBQwJAwIHAAABAgMAEQQSITEFBkETIlFhcQcygRRCkaGyCBcjNDVSYnJzdLHBM1SSk7PR0uHwFSTxgqIWJTZTg8PT/8QAGgEAAgMBAQAAAAAAAAAAAAAAAAMBAgQFBv/EADQRAAEDAgQCCAYBBQEAAAAAAAEAAhEDIQQSMUFRYQUTInGBkcHwBhQyQqGx0TRScuHxM//aAAwDAQACEQMRAD8AeNSpUoQpUqVKEKVKlShClSpUoQpUqVKEKVKlShC+Sbamvl3A3IHTXTehP2q8Njn4Zie0LDskaVcp3aMEgMNmU9Qdt9CAQE8bePG8twTvcHCGPuXNnaJuxysb5gGBvcG4uDehCc1SqXCMemIhinj9yVFdfRgDr51doQpUqVKEKVKlShClSpUoQpUqVKEKVKlShClSpUoQpUqVKEKVKlBntM5xPDMOpjVWnlYrGG2FhdnIGpA0Fr7sKEIqxmLjiQySusaL7zOwVV6ak6CknxHmvjXy/FRxTKBG91iPYsuR2QRBSRdywki2O7i9r0I8T564hiD+FxJIEgkVckeVWXVSBl2XoDfUA6nWshOKzqSVlZCXznJ+D7wscwC2ANwDp1ANCmExeL82cSi4XnlxA7XEYkqpTKGhRVbOndAKPnUCxFwDvf3RrhHPnFYwIo8VIe0IVDKFlIJYC4eRWO5trcC+21DC4h+07XMTJmz5yczFr3zEnUm+tzXWLicyoEWQhQhQDQ5VZxIQtx3T2gD3Fjcb0IXpjmXBTy8LmhJV8Q+GKMR3VLlbMwvst7n0pXcp4GSXlviCkWXOZUv1CLDIfS+W49aqRe2LGGF4pYYpGZGUOt4iLgjMR3gxvroF2+i1wnn3BjA43CydqhmjKxnICCTh4oiLqTlJdGa5FrMNdwBCY3IAOE4Rhu3umVLm/eIDsSgAXckMoCjXUDesbH81SS49IlaWCExlAHKxfhTdlbOElBOQXEb5dwbEZrY3D+f8EMDhI5MSTPh8odezl74RXjvmKZScpD6np0Nc8ZzVwxpw3ylihlWdiySWBXKQlhGWJayoQB7obyBFCNuK87R4OdYcUvZIY8xlZs2uwGVFO59PQaVtjjuHzhDIFZiAocNHmJFwqlgAzWtoNdR40h24rB8peT5eJsxRgZIZrAXIaJSwBTuKi57ANZb7Woo4DilMxnacLgYg+GgzKZI1DFnCEWtlyKEvcEgwgfOBEJy1KDuQecP+oIwdcsq9+ypIqmNiQhuwsTowuDYlSR1AMaEKVKlShClSpUoQpUqVKEKVKqY7HRwoXldUUdWNv/PoKEMX7UcDHa6zEE6EIBe3XVgR8QKEI6qUKYP2gcPk2nI3uCji1t/m2rL4v7UcLGPwQZ9SLkEDS19NzvsbUIR/Xmv2r8w/LOISBTeKC8MfhdT+Eb4sLeYVaKOO+2KQxskEah2BAk1OXzFzv1HwpTE+JJPidb+vjQpCldsJCGbW9utunh9dcaOOXuS5Th1xLNlEmqxm13TTvb6b79LjQ0KVjScrz5cwTS2lxqb6i1veNvAf7d4uUJFjzyaXGgW+ZTa/eVgt9OgN6PV4JGsJb8JEdl0diCCQO8G236jQ671r8vOpH4WaNifdLqOmmhI3Pr8NdRRKWeD5bQ5VltfWwXRrC2u/puKsYvkwQo2YMSb5GFzp00Gl+n8KdEXK8L2LrFJte6KfTa3TT4Vn8a5fdQVihRYgpIMbNmzeGTLlIt432GlChKHhPIE0yhgVsQDbW+vTxFYnFeATQPkZGG9tNNPPw33ttTt4bwaJX7R52bMApR0VrN+sovprsforrzBwCGWPuzhdL5s4118DsOnoLUKZSN4bwNpwSjKCPzrjruTY2HntX1Lw/EwxMM7BS/eiViwLLsxUEroRbNuKb8eHgzLHHrIDo8TZQzWF73ID+lz18DXaDkR3Yu0ia65CL3296zEfEDrQoWF7LOa4onMeKDQNIqpE7C0b2LG2fSzEtpfTTclqc1LbivJUOQ54ig/PRhl9TmsfjvvVTgXHnwXZxRucThtFUKTJkuLLaQk2T9E3tsNstCE1KlD3AeLK8ZdmPflfLoxsL3UE5bLZbeQta+hrcSZWFwwIva4IOvhQhdalSpQhSl/zNzthkmxeHkfFK2FjSR1iyL2ivk9w7kjtFuCR1te1MCkv7QvZ9LiMTj8UZIojJ2HydnlEYbKipKj32BGo8So8aEASYCNI+SMLPkxGbEXdAReTUBsptsbbC/pQry3y9wnH4jFRRDFB8NJZy8gyuSZFzJqb+6dSBuPgeYHjWHjw6J8ow5kSJRbtksWVQLXzePWl57MOEycPxWefGYZ45MMVe08d0k7RmA9676EnMer26VXO3iPNN6mr/afIrS5i4Lw3hphjEOJklxDN2aQ5XZigBYkvba469fDb94JyRwvimHTFoMRkkzWDOFKkEqQbA9V6G3Wr3O2CkxmIwOIwDQYhsI0pePtlFxIEANxe1sv1itj2ecHfh/DYYMQyBo85chu6uZ2Yam2wIv51YX0S3AtMHVLfD8B4I+L+RLFjDN8oeC3aLa8Yuz7+4Br4+VbXNXs94TgMK+KlTEsiZbhJAWOZgotew3PjVDhnA2g4u3EFxGFKti5iy/KI9YZRYNvoykk266UW+0uSLG8Omw0GIwxkcx5c06KO66Mdb+ANVzt4jzCZ1NX+0+RVaD2Q8MIVgJ9QDYyfHXSik8swnLnaRgtrAtlGmwIUC4Hga74DikDBI1niZsoGVZEYmw6AHWu0XE4WVnEqZUdkZiwAVlNipJ0uDpUggiQqOa4GCDPcUGcL50wTNHCkMw7XFyYUXCWDxhCzHve6c4sd9DpWvzlicJgcO+LnhZ1UqCIwuY5jYbkAgE9TS84Ny3NHjYs8uEEEWPmxXajEKSwkCALk3B7g+ny1OParw44vhzwRvEHkZCpkkWMHKwY2J02okILHAwQfIrQ5M45BjYpGiikjMUrRSJMqqystiR3SR87x3vXxxXm/D4XG4fASGQy4jVT3bLmLBQxuCLkECw6Vk+zXDR4GGeCSbDqpxUjwhZUb8G2XKCb3J0O+u1DnPnL+Jm4i2KWfDp2L4YwxvKil+zLMSSTeOzM1vG9GYcVPVv4HyKZ/G8cmGw0s8mYpEjOwHeJCi9hm0J9dKxOVOJR43NOMNiILqjh5o41EwfMVZSt8xAGp3AZfGr/HMRDiMLPGjQz3ibNGZQoYEa5mU3QW+d0oN9l2AXBPjDI+GgimaMwwLihN2eUPm7xPW41308hRIUCm8mIPkURc38yYXBT4WKeNmfFMY1ZVQhbFBd8x0HfGwOxrrjOBw4WKWcNPaON3KxlQSAMxCiwAbu6bUD+07gc3EcTmw2Kw4RMOqRgypeSQyqxA1umgBDDW6AfOpoYTGxTpl7SN2Kd9UdXtcWOx26XokILHDUHyQE3PHDUUu8EshGFXFZpAkjZZHVMgLPo13Byju2vrR1HwmLuyZSrADe2gsdCLFR7x2FJjh3s4xF4I5JoGkXEdnMglUk4ZTAwGXe4MbHL502+P8VibDTpDiIO2aJ1jvKgAcqQt9dLGiQp6t5MAFY/IPGMHjlmxOFWZMj5XEliWsCQQLsbHN4g3Xyrpxbj+HTAHiGIw+JjUEERuAJkJbICt2/B6m/vCw+isH2WcCk4c07TzwNDLHABIsiALJGtimhtpcjNu2UE70W85Qx4nAuBHFiY2Kkq03YowVgSe1X3bEfVaiQoLHDZWeUcZ2sH9BiYcjZAuJADkBVIIIJzLY2vfcMOlbtAnsk4Q+FwksbvGc2Id0SOXtxEhCWTN4ix+kHrR3UqpBFipSG5x4o+IxUpZmKq7Kg6BQWAA9bX8zT5pIcT5UxjTSlcO5Bkcg+ILEjrSKwJheh+Hn02VHueQDAiSB5ShoE+dfuvnTU9n/K4SKQ4rDL2hYACRc3dAGwa4Gt668/8ADsHFg3PZRRubCMoiqxa4PQbWvf8A8Uvq3Zcy7B6ap/MjDtBNwJBBF/Qb3SqwmJaN1dGYMGuCDqD/AM6UVe0Djsk5hS+VOxjcqNAWkXMT56MAPDXxoQXcetbXNX9JF+7Yf/DWljgt9Sk11em8i4DoPl78bQsW586/dfOi32Z8PjmxLCVVkAiZgGFxcMguRsdCaPuZOVIZsNNFBDh4pXQqsnZqMl9L6C4Nr2I62pjKZcJCwY7plmEqdW5pJibEbrz62Nk98NbtdI1uSyD5z22udwfNdtaKMNxZpOFYWPRVWWRVVUNgoC5cze7I/eZiRr3tRc3I+/C1DHKTYRGMeIve7X2JK2X0onmQLw7DKosBPKAPRYaC4ZSArjDVfmKT6pmCedy0zfUXB0gRlGrRl3cbyIRg0nhaWSRljbswL++ATa2vWsriuDl/7KCXMjdmFKkaqGllA0Pl9QFNrhmLjiwcDyOqKIYhmYhRqq21NLr2juJ8ZD2TqwaNFVlbML55BuPA0VGtABWHo7pDEVqxp1LgFxDuEAiNhb3ZEEfsxhBB+USmxB2XpQrwXggx+OnV5GWxkkJABuQwHX9b6q3ouTuJhgfli2BBP4aY6X/Vrh7Ofylif1Jf8RKCBmFoUsxFZtGq8YgVCG2Itlv3b+ix8DwgRcU+SiRspzpfQGzxtfy6/VVznXk1MHCsqSuxMipYgaXDa6DyqzJ/9Qf+of4dbvtY/FE/br9mSjKMrjzVjjK/zeGbmMPYwu5ntFZ3KvI8bR4fEmaTMckhAC2uCDba9tKo+x/+nn/U/mKO+TfxHD/s1oF9j39NP+r/ADFXDQC2PeiyfNVq2HxnWOmMoHdmcs3iJI4li7ad3Eaj9m9duTOTkxsLyNKylXKgAX8NTf1+quHE/wApYv8AVxH+G9ZuCw2KXCyTxuwhV7MBIRvbWw0I1UX86V9y67usNBrab8jiKYB87d50VbBufk04ubdpGSPO8n+ZpjcPP/yE/sX+21YfKHKa4rAyN2tndwALaIUubHXqGv5AjesB+BSri/kHaC+YC+uW5AN7fGrAFomNbJWJdRxb30w+Cx4ebE2a0A/nf0IKYPsl/FJP27fYjo3rA5Q4D8ig7IvnJcuSBYXIAsPKwH11v1optIaAV5TpGsytiqlRhkE2KlSpUq6xKvisSsaNI5CqoJYnoBSP5v4+2MmLahB3Yx+aPE/pdT8B0oh9pfM3aMcLEe4h/CEfOYX7vop+v0oP4PwyTEypDGLkn4AdSfK2v+5rLVfmMBev6GwAw9P5mrYkSJ+1vHxHkLcVs8jctHFy3YHsY7Fj4+CjzPXwHwr69pMYGOYAAAJGABoAAo0FNngfCo8LEsUY0Xc9WPVj5n/bpSo9p34+/wCrH9kVLmZWc1GAx5xePc4fSGkNHiLnmd/LZXvZH+NyfsG+1FTbNKT2R/jcn7BvtRU2zV6P0rl/EH9Wf8QvNsm59TRVh+DzYjhsZiTOUxD6AgHVY7EXIvqLW31oVYXYjzoY5r4320cMSZuzQyNrsxYgXA9F386TTbmML0nTGLOGph7YzZpAO+oP7HMJncxT8UTBOk0LdhEgI7gFsg7uYrrYW38qXfLfHcXPiYY82ck2jWwGWxZxltr7xJt1uaIo+bpm5dlw7Z5TmEfamSM9kpcFUZS5lNwrgHLa1gDZaDvZ4+XiWCsiOTiIxZ9hdgM241G48wNDWgUxF15V/S1UuaWANAMw2wJ3zDeRbuTyj4nxvMLxG1xf8Gu3XpVvknhE8WOnkkiZEZZApI3u6W+oE0nOK+07iZxbypiyqrKcqKQYrAkAWtZ1t1O++9b8uI+XYntIQbYiQlASBrI2gPhrSqgykHVdLA1RjhUpBrKYy3LW8/8AIaeNpTAl4JiP+s/KOybssw79v0QP9q1/aTgJZsMiQozt2wYhegyuL/SRS54/ylicIgllKlS2UWbNqQ3p0Br64jxaZuHwRs5K9rKpBY6hFiKgnqBnbQ+XgKrngFpGq1DBuqVKFelUa4MhgsYhocZs4yeVk2+V4WjwkCOpVlQAqdwRS04dwfieClkMERuQQSFVlYX0Ivt4+OutUuGck4qeETxlcrAkAta9iRtt08aq8tYp17eNScrwSgjcHKtwbbXGXf1oc6wkQpoYQU+uNOo18ntNLbC54OPE627tVtYDl3HSSzTzREM0cpJIALM6soAA/W9NKJeTuBSDA4jDzoUMjNYNYaFFAbrsR9VZHseH4XEa/NX+NZftR/HjqR3E/hQAAM/vdVrNq4jFOwWYNAykODdIAIgZufFEns3wOKwzSxzxMsbAMpOwK6EfEH/21WxPCpjxpZxFJ2XaKe0ytltkAvfbfShbmgyz49osxJzhIxfQWsAB0Gu9fnHuUMRhEEsmQqWC91s2upG9vCgugQNAU1lAOq9a97WvrMy5Q3jFxLtdBsnrUoM9l2Id8F3iTlkKjMb2GVNPS5NGdaWuzCV5LFUDQrOpEzBhSg72gcy/JYuzjb8M40I+Yuxb1Ow+J6UY1595jnd8TK0hObtGFz4Amw8gAAKpVfAgbro9C4JuJry/Rt44nbw3Pcs5QSbDUnQDe/8AnTo5E5aGDhDOPw0gBf8ARHRB6dfE+gpT8A4oMNMJjEshGqg3AB/O0BuR0+noKMfvpy/1dP7VJplrTJXf6Xo4vENFKi3s6uMi/K5mNzxPddpUlfad+Pv+rH9kVsD2py/1dP7VD/POIMuJWUjV4YXt4ZkBtVqj2uFli6I6PxGFxGaqIlpAuDuOErW9kf43J+wb7UVNs0guWuOvgpTKihiQVKtfUGx3GxvaiiX2pTEECBAbaG5NvO2l6Kbw0QVHS3RmJxOIz0mgiANQP2l5jlukgtc2awva5vp/7qX84kUKr3AFyqm+l97A7XtTF3PrQhzRiYZHUx5i6jK50ykADLl63GoJ2OlvElA7JvxHRY5japN5gDjN++3qsIMdr77+dW+D40wTwzDUxSJIP/Qwb+VF/I3swxfEQJT+Aw52lcXL/qLoW9SQPM7U3cb7IeGydnZGiyZv6I6Pm1u/aZ2a3TW3wrSvIyvPqwz8RxjCKMNNiJHcItlFzdiBewAAvRvwXAy4DEp2khdsPJrGCAl0Yd0GxtrpeiWb2PYjByrieHYsdoh7omQXW4IJBsysQDcAqPptQ/ynBK/EGGLdpGOLCNnBW/f791Nsoa40sKTWnKux0I5nXkOaT2ToYgC5m44R4+KKebedvlsIi7DJaQPcyZr2BFrZRbf6qxcZ+JYf9tP9nD0b+0rguHgwqvFEkbGUAlRa4yyG30gUEYw/9nh/20/2cNSHyCZXpejn0H0GOoNytzG0z9rp3P7Ta5G/JsP6jfaelPy4hMkgAJvDPYDUnuNtTX5EYf8ATYdRor38u89Lz2Z/lBP1ZPstV3iQ0Lm4N2Q41w2JPlnVDljmN8C8jLGGzjKQ1+huCCPWuHH+LPjZzIYxcgABQTtoAOpJNGvtXwMUcULJFGjM5uVQKTp4gXPxrV9mmAiODjkMcZkzN+EyLm0NveteoDXTklaTj6DKQ6QFPtOOXW++u0dnhPcgDj2IaHiLyZQxjlBsepUg2+qt1/adMdDh4j65j/OrmP5lX5e2HbC4YgzZC7R3Nr2LE+OtXvadw+KPBAxxRoxkUXVFUkWfTQUXEkFLdUovdQpYijdzQGnNtAvbw1W3yRxk4uBpWjSMiQrZNjYKb+uv1UR0D+yT8Uk/bn7EdHFaKZJaCV5zpGk2linsYIAKlLbm3kF5ZWmw5HfN2Rjlsx3K6WIJ1set/gyaE8aokQzzBX7pZVYArGLXAF9jtdup8AABFQAiClYbG1cI7rKZ7+BHNAn3usd+Yn94Kn3usd+Yn94KwuF8KWIs7tEvZrGAey7QnPnLKgt1zDUAkDUbEG/huI8QPcTAQPoBdI1um4s9mZUbTa/d9al2GA39Frb8VYo/a3y/2rw9neO/MT+8FE/H+R2xEEBUhZo4Y42DHutlHiL2IN9ba0K4jDYhygxfDMmUgrNh40nK7GxVQwtoPeDD7VUuNcvJi4QsZSORf6InujEJ3AoYlQRJnsLPqGZhswtUUWpdX4ixT3NcQARJFuIggg7LQ+91jvzE/vBU+91jvzE/vBSqwGCEkixEhGJIBK/O+ap6i7AC/S5o84DjYFwcUsyxm0jRhAou5UaAkiwHeDF9bd0VPy7eKYfinFD7W+/FbH3tcY4KHImZSMxe+W/WwFyayuC+xGaPEwnFSxPDdmkWMtchbWXvAaMSAbbC/lRTwHBw4oCaNVyjMCmQADYWb599iPIk63Fb/LfDPk8s75ES8cQUDui15d23NzbUgbbHc2awNOUFYsV0pWxzmmoBaYhbeMxiwgKoGgACjQKBsAOnpWeeLOTuPoqjii7uc2Vdfzrj4GwB+mpImXci3jt/OtjWNhZVt4LitzZ/pH86GueuU2xMiSQhRI/dcE2BsCVa/jYFfPu+FccBxLtmIAyAWKksveUlgCfC+Um2ultb3AIOIosuElRmEtkDEC3zLNb10pNWm1wT8NiamGqCrT1H5tp779QEBfe3xvXJ/braxXs9lbBxRh0MqOzNckA5wgIDWvcZBrbXWgHmXjcQBwsODW63He94WuDdVOZtjqTpvbrXzyfKkcgvhcMb2DEgki+urPcg2Gg0Go0pAwzVrf8AE+LqZXGBBn8EXna6KPvbY3xj/t/7UQckclzYaftpiuikAKc1y2lzoLAC/wBPlrjvhcNFK2aNRcsEVUHfVsjCwYW7utybBb28L24uXxJGQ6RBjZioQDJsQC1ruQdzoNTp0ECi1pmUV/iTF16ZpkCDa3s9y3vaNwWbFxxLCuYqxLXKrYEW6kVf5F4dJh8IkUq5XDMSLhtzpqCRtSd5s4bH2wLCNrkLGkCKXY/OJC6sBYdNL7amukXLAXA4cMATnd3GUFlV7WtcXuCFNvEmmikM0ysLul3uwrcOWjKDPPfnG/BGnNHIU82IeaIoVc5iGOUgncbEW8/8tcn722N8Y/7f+1aWD4OnyQQvFFn7MBj2a2JPp/zelvx7g+SScplBjIdWW6lMoBsp3uAym++i63qnywdJW6l8UYqmwUxEAAenLZPfkvgbYPD9m5BZnLnLsCQosPHQb+tEVBvsw5gkxuDzSsGeN+zL7FrBSCw2zWNiRod9NqMqkNDeyFkqV3V3mq43N1KFeDTrNh8t72GQj00oqoE5VQx5x81grjwudD/AfT8aio2Wk8FnqOhzRxlA/G+WUhVZJ2ORR3lJtnYsQACB3AdyVBNr21y1rT8UkkWMYa8UEajLlXKp/VXcr0sRc/EVt85YOOURmYt2SuLgbE7DNodLm21rE1y4x2UJRbFQwsnhobAaafO0G9Oa/PBIuZ7lz3NyyAbCFRwfHMXGq2cSZbZsyrrrrYra2xABvcqfAA70bQ8QQNfsphYZlOp3ujA2JBF9D5kG4vVCaABLWsxBXNfodwfLz116b1g4rEOqskThBG4IYnI2Y7AbtYX2sQfqFcgddtjxVhULRBuOC+OauQDLK08bLHKoLugTRyCTnW1t9L6b3oVwPBp50gWIWjjBd5jbJGJSFfun5wYNpfoSLdHbhZjLFFKw7+Wzgdeht5XFxQxw3haiSfDlSEDCVdSA1zcJpYlQVuQdO9rvVWPsQdR/wq9RsERofYV3gnL3YqUjcjS2vunL7t7dStwbbaaaC9vG4kSwu+VQ0cpDpJpqLKACbZWIK5TpfN+lVhJ7lVUadelrbA+fT4GhjnDg3aJ2kQcqtgcOCyrNdu+coIDPax7wIIVrjqIY455OqdSjQLLx3G1YBsOgQK5DO4Mga2YZI1QF5D87Qi2XU6EVUg4jMzO0cztmXtbhFysiZUJjBzE6j3Da+pvrr14hjQ4wzRlFJksje4qlo5FGYDu2FwLAdLb1xxERjZ41MvduDkLRqLIrWAQhI8wIRQRvrdzcVsdI3TwvrDYjEJ2LhbgwI0wVe/YGQ3ynfV7kAXsLAUccpcXTEKmQmQMtnF1VUzC5Uhb94Dcf+aFocQ0WLEbuJCIWtYWYC8dgwFlvub31voBav3E4SCaVpEQQdjYySLJkaV2zBUYe4x0ZmNjooXUMQKPBDUEjUob47xNXZzCwaNcoBNiLBQCwF8jG4OosD46V88OwaqpMjLHGiBzbRlF7WOnUket7DerPMCxkoQ4vdVGUWYhbhSqbIB3iSospFrC9UsZhpHw7i2dI5YpcoIbKtnDobWGjkNbY3uLjU0AIFlzddVtcSxJZo5oleRIwpWRk7z2I7oZiLkm+g6hdDqAxoGSVDf5wva/Q66EUouESMSTIoXssgSMZ2ETIcxurGyiwKkeJFtSaIJecJFlLpaXD5O5ZAhuu4a5zX0J2ta29UfTzaKzX5TdEiPgMG1+4JGGrtq7XIv3jqbsRe3lerU+GEqXAClrG/lbTrobfC9JbGcbOIHZtnYq7tFsxGdr9e8SPJrGw08WTyvzYk6ZioRRZe6cyg/QCvow9CaOrIu03QTNnC3JELoVUX6DU7UO8wcNSVWB2Ygm1u9bTf+fkPCu/MvHY0jALe/tqdha57o21GulLeDjMnbZg5KncEkg9NidLaaeXrTaYIuUlxnRNL2IYcx4bFRnXLiiB6dnEQfje/wAaZNLv2LS54MW3ji2/w4qYlKd9RXWpGWA8gpSa5F5qEsuIw8h/CQyyAfpR5mAI810U+WXzpy146xvEJMPxCWaM2dMRIR/aa4PiCNCPA1W26iozOI32XpLGzAR6qTr5fT/A0Pe0a4hhlsSscqlwB83Q3v0Gg+nyrjy/xhcdhu1hOvWIm+RwLlfMHp9PlXbl7jwxMb4edBmUFMpNi6nS1jbUDQ6+elXDMsOF49Vzy6SWustzCpFjIEcb2BB2I2uNfTYist8PkKLLHfWwJ2DC2U3udzYb62Hwu8AhiRVWGQ93uqpsNvmuAAQwHUi/j59+NIs8MiG+vdIBsUO/huNx6VQEtdA0/SkgObJ1/a28NMrLp0tcdR6+dZ7grJI1rg+e3+VCXAebezZY5WUyMSr5dLnMFTQ9SLD+z0N6KcJjFxIvGucMLXFu75NuBY3033sDSzSLCbWThU6wAbhZHNuFdsMxjn7EEZXJuRZtNbaoQTfMNAL301rnw+TEiFvlwQGEgpJGT3xtnsNQQL6aXuLW0NFMWEVNXbMegOw/zPmfoFDPMuNDQvbUsTb02H1WrRTplxAKdTo5e0fJBnHYOxK5AvZvKBky9oo7h7y21OYBiw63DDretFicuU9tF3RbMZY2ZB4K0iB11sbEG1XJsYQF7uZAb2tcrfqBufGw11Nr7G5hnVxdSG9D/wAI+qt3Uwdff8clOeyzI55O0RIjbtFkHa9+SzNlbMXYL2p7oUECwuBc0Wy4PLhSMLqI37MqCLjP3pJLtexuQATtdj1NZMk2XYgtsbahfj1P+9/A6nK+MIWRRoSxIPgVNgfhlBpT6RyypgPlp3VPgvL6zqkmVFCgAMvfDkXIA71jEGOa1hnYC4AHetR4jErM8UUcSggFpGR1zG5BI0IJygG40uRqaI8TgVxMV45Ww7sL3TVb9cyXGt73ykEm971j8Y4fIF7PEEhWsgcAujFjpd1sy69HAFyAL7nJHFZqlJzNPx7/AJQ1x7haoyoli2UPK2p1NyLKNxowtlJ1GugoKPE5nd+yYuzjvWS4OrX98abnXS1Mubg0ubLmYX7pYKpJC66toVv4gjX69LhnB0guwQZjuQAD0679PHpTSQBcrMDySy4XyXiJCrTJJk8Ay3troCx0HXT+dbzYVsMe0GjHRiQEDW1s2UlS1/n2IOoO96N+31GYC5Pht6km59ay+NYMSgBmIsbrbT/nh6VLeBChzt0u+ZOI9t4qwOo01t4kKNdbGxscvlrkTDsRnOndufjt9NE2N4ZlLMxXIBoTcnQn6Nx1vp50v+PcS7Vsqm6r12zHx9B0qzzlEplJhqHKNN09fueZS+BxDHc4pv8ADipq0p/ucfyfP+9N9iKmxWVdQCFK8XcxfjeI/bSfaavaNeLuYvxvEftpPtNQhWeWePy4KYSRm4OjpewceHkRuD0PxBdOAXB8SVMVGSr3Fzp7w1yupvY+I6jYkV57rZ5e4/Ng5e0iO+jofdceBH8DuOlWa6Fnr0A+41T0m4DiFJfDYvexySDOAQdlYksB0sb+tbcSmYRzZGSVlsUNhm0uQ1zbSxN76a23rC5T5vhx69w5XA78bHvL5j85f0h8RRHPJa36rEevdX+DmgySB7/2s1NgLsp8VS/+GcO0wxE2slrMinRtrZzuxFgRa1j471uPi1UBUAAGwAsB6AUPQ4khQPDT6NKjOx3NPFNdFtJrdAreOxhfQHfT0/4Ln4VhcVbugeN6v4pAUtcg7hgbEHx8/Q6eNZWIUkDMbnobW06fE/D0p1OxVnWBWTGgyDx1Uedrj+V6xeI8PUSd4BifdJAub/76fRRJhYhd/G+nkCBt4XINUuIN+GQeGX7VXrgFl+PrCjDEioY4E+QldcNDkAUnwA6fCtXgQtH+kdT8df41TxUYKMCNwR8Tt9dq0II9NDY9D4eviPKrv0hJZcytbBYkoxXo3eHkdm9Oh9S1bOGx2a4OoIIIPUeBHWhjCyjr717MPD0/R8P871bE9jpWYslPtutluGLcGKQppbsz3ktpt1TawsbDotVp8MwNm0I101DDXUeWh3sfKuUPEfEaV9Y6RvwZa2qMrX6sMhX+L0hzC1ZsRSaWFypYmMA3BrE4xxEILnb6aq8SyRB5J5i42s3cRfHKp+rU6eO9LDmbmgz/AIOK6xjS/Vh/IU2Q0XXPp03VHdldebuZzOTGmibE+PlQlUqVmc4uMldSmwMEBei/ucfyfP8AvTfYipsUp/ucfyfP+9N9iKmxUK6leLuYvxvEftpPtNXtGvF3MX43iP20n2moQs2pUroENibaDc+F6ELphcS8bh42KupuGU2I9DTh9nPN02NLxTBc0UV840zXeLddgdNxb0pLUzfY3h2DYiUgiMqsYaxsWuGyg7EgDUeY8asz6ggNBIKY8MozMOm4/wCet67vILVmhrP6g/5/511aStuVMmy/cRKSptr5ePl8dqqynNtsf511F/WvyGLUr8R6f7HT4irgQq5gbKlh0tIR4r9k/wC5rJ4wD2j/AKIH2Qf50Xy4K4VuqsPoOn871n4nhhLubbn+AA/lWfEvlvitGDaBUnl/C5yJfLpoWFj6Xb+VX0FfMGDY5PKME/8Aqt/pNdcSMoJ8NvM9B9NPL5usrWZRCrr7xPgMvr1P+Xkc1WBJprXBbAAa/QdfPaoW/RP1f51MKF9ytpvubfTpXxznxYwYHt1GbsnUlb2uGDoPTvEa1yxZ29f4XP8AKuEuAOOjxWFuoLYZbFr2D58yXtcjVN7eNLqjsyoIBBadCkrxzjk2LfNK2nRRsv8AzxrJqzjcM0UjxtbMjMrWNxdSQbHrqK+ZcOyhSysAwupIIDDxHjWEmdVLWhogLhUqVKFK9F/c4/k+f96b7EVNilP9zj+T5/3pvsRU2KEKV4u5i/G8R+2k+01e0a8XcxfjeI/bSfaahCzac3sWx2GOCxeGnRWzvdwfnIVAAPhazEHx8NKTNFvs0b/vVUglCjZ7dABe5+IA+NWaATCEP8WwnYzSxa9x2UX3IBIB+Ip1TTyGDC2URlI1JiWyJ3gpYKBoCD4+evjucwcm4aeVMZHEO3js2UAFZgo0DKRYuB7p8QoPiMqPEyZRnjzqQCHW+t+o3PxIB8qdQbeSpiLL6+Uq1mU7MLjw6EEel6tt/GsXE6XK3BsRqLX8j41r4dw6gj1HxrYQoa6bLpCL6E1px4DZhuuvr4j4j6wKqYWO5om4ciqpd9FVSzHyGtIqvgKYAuv2LBqIyWICkbnz8OpPkKqNi8KHKlzmGpGRutzfXUjzoW4hzDNiixiZIlBy97vFPUD3ddL2OtvhlS4eYJ2hctI1gWJPcB1NwuwA3IIB0vYa1jfmJgpIxO7T+ExsHFFID2UiuQBoNwOmh1te9UcZg+9tt/E/5D+NK3g8whkLxz/h10XukAs17kPci4a3vCzXI1Bpt8H4gMXhlmy5XuVlXbK6+9odQDowB6EU+MvcppV85h2qwpI7VwIrXxkNZpWtDXWTSFm41wGF+gJ+iw/nV3gU6xtmbRpCL738APgB9JPjWXxD+l1PdVQfXMTp56qK74EnPm2tu3RB5eJ/5tarG4UCxS4l5WbD8WihxeWRHbtmykkMhLHvXHduVsb7Xog9uPHFk7DDJayEva3ui2UegOun6IpqYfBxFRPIi52iszMBdU97JfwB1PmL+FvOfPsjHHTBhlykKq7WUAZdOmmvxrBAAQhypUqVRC9F/c4/k+f96b7EVNilP9zj+T5/3pvsRU2KEKV4u5i/G8R+2k+01e0a8XcxfjeI/bSfaahCzaa/sIwqdpip3GqokSk7fhCc3x7oHoT40qKfvs1gTDcJDEG+IZiW0YBnORAbHTQA+pte5qQCSpEborw/EfksnZS6JcGN/wBE9D6H/lqERHKRlWVQFOW1spFvhcaWIPUEHrRrKUbuyAAaFGJuCDp1trtceYrF5swT3RobZshuPzgpFtfEXNaKJgyd1L42QziVt7zlreO1WuEuOzS3S4/skj+VYfFeKJBF2rm56Dz8B5nx6b9KscoY4y4ZHawLFzYbDvtWwuBOUJI4oz4e961uYHYYDEGMXbKugFyQWW4+i9D3DZdaLsAyujRt7rqVPxrPVEEFWeC+mWjcEfhKTMFYy5CiXKEjIQjMQDnu2fYDYDqANK7cx4HHOVkRWkjRVyNGO6oHmDqR47+lhRJxXgCmWSOQNlLZjZWYhmJOePKPdz5SdxYkEaVp/IJI4imHjyMw7zXBLBdBcnqRa9hm8TtfK93aB/ekLE11oShiVpLlrhrWBt7+h7unztNra97roWr7Kp3kw+JZiSDIpBPU5bH6gtDqYWbDBQ0SSKj3UvmDs+oAS19b666m9hvR3y1wz5Fg1jcBZHYySKuys3zR+qoA+Bp7nS3xsr0DmqW2X7jRWLiXt61cx+KvoKyA92t1ptNq2ucs3EKzSGynS3esT0G3nqdfOvpMOzkxWZiUbQa2FrXtfu/RQ3guNF8disOTosj5W2sEOVgfK4uPj5UwOUtEkCi0jMALjZcqnM3xbbxFulS6oAyR3KsSYWjwzEiSPI4IVACxbT3enmBb6qXftb5XR5JcWCIysSOxNyJDqoW3zTZVAOt7623ph8ZKRQSjtLZFzM5FyWFm1FxcaC/kbDyDfbBjrYV00uViVrdSWzWHlZT9NZLO00E/pM2ukZUqVKUqL0X9zj+T5/3pvsRU2KU/3OP5Pn/em+xFTYoQpXi7mL8bxH7aT7TV7B+Xyf1Wb6Yf/wCteSecMBLBjMQk0bRuZHbK1tmJIIIuCCOoNqELCpreyDijrDiUcl4VaO6b2EmcMR1FrA/SaVNE3InFjh8SBeyyAofC51U/2gB8TV2RmAKE+cLj43sudS6DK6t3Qyt1XTQnKGA2t63qhHiMjFX7EqASkmZgxXTQ5Vv4dbG3loJ42U51cC7jS3Vl6j4bi/1XqvJiDI2YXWNL2JOXXqxvsFB66Am9azQAMSq9auftA5niibsVweGcshOdlElgdNCwzDUH3SLECvrkj8Qh9X+01A/NvGBiJFRLGOIEKbe8WN2Pja+w8r9TRxyOf+wi9X+01Uof+hUlEuGnsa3sBjrdaFlNWoJrVqewOCqHQj2PFpIoD622INiPQj+GxqSMmoEpHqoJ/iP4UJYfGkda6txE3OvX+QrI7DyVJYx1z6+iJQkUbCTV5Beztbu3/NAFl8L7+dUMdjr9ayZuIk9aqyYimNowpaGtEBfuLnrnhjro1j42vaqsj3r9gbWtGW0KhN1kvx3hxxTpNh0ixKStGHjRgZcxtmYR5Q2Ym9m160RYDj+HQZAWAYkKACQ3mys5J16XG4FvFJ85EjH4g7HtTb+VbHCeOjEL2ExyyXBjk6ZvO1rXGmm9zsawMAdLT4d6YSRdNTG8ZQsI0XPbvuCMoZraF/AXtproALWGoF7T8UTClzq8tz091SLAeGv11pQKYLvIwCW77E5Rf46k+Hx8qA+beOjFSDKLRx3Cnq17XJ8NhYUx7WsYREEqMxch2pUqVkUr0X9zj+T5/wB6b7EVNilP9zj+T5/3pvsRU2KEKUsOauI4HGOwxHD5MQIGYZxdctjY3KkEKbXsx86Z9APMkpmm/wCn4NVUuc2IdFAAHUNa19wT43C9TS6hIFiuh0dTpVKhFRsiJJkgNA1JjlYc4Q1Pwbgy9iE4ZJIZoxIFV5L7sLWDkkjKdulZfGuSMDjcJPJgYWws2G7zIzMwkFicpuTlbum3nod7g4XBLDxXCQp7qYYgdf8A72p8ydar8H3436yf/vqjXOzX7lsr4bDfLufTaZDGuBJP3VC2CNNPFImTnTElAoyA9Xy3Y/Tp9VY+N4pNN/SSuw8CdPgNhVGpWpz3O1K4UBSmzyYlsDD55z9LNSmptcrC+Cw51vlbY22ZhTsJ9fgodothjpX6r61xynxv6jX6rV2RL10AlkKyDbWuEjnU769LeA8TXXPVcybjz/kKhRKsrtXyzedcg/nX3UqYX5mveuiCq5HW5FdIlBIuL+utCISr5+/H59tSh080Q0O0R+0D8fm//H/hpQ5XIf8AUU5XcZxGWUKJJGcKLAMSbf7+dUqlSqyhSpUqUIXov7nH8nz/AL032IqbFKf7nH8nz/vTfYipsUIUoHPI7iWSWHGyxdoxJCg31JIBIcZrEmjipVXMDtVooYqrQnqzE62B57ghBWN5Md2ik+WSLLHHkMljmbVje+e4NmsdTcVf5e5WXDLOHlMxnP4QsMt/ev1JJOZrm/WiapUCm0GQEypj8RUpmm53ZO0AbzqBMTeNOS888a9jMhxzwYWeMRlBIglzXAJYFSVU3sRv1BFfH3hMd/WMN9Mn+inPJ+VB+6j7b0RVdY152+8Jjv6xhvpk/wBFaOE4W2GiTDsQzQl0Yi9iQ7A2vY2vT4pM403kcnrJIfpdjWrCfWe5VdoqFqsoNK+XFfWH0rcVHJciDfavwDUj0P8AL+VWmFV5B3j6D+LVaUnJC/BXRRX4pr8Mnl1oVsq/HNfce4qWr6QaioVlk8Q9lOK4jK+KimgVHIAVy9xkVV1spHTxqv8AeEx39Yw30yf6Kc3In4sf2jfwWiOuTU+s96aF52+8Jjv6xhvpk/0VPvCY7+sYb6ZP9FeialUQvO33hMd/WMN9Mn+ivqP2DY24vicOBcXI7QkDrYZBc+VxXoepQhYnKnLcHD8OuHgWyjVmPvSMbXZj1Jt8AABoK26lShC//9k=" height={100} width={100} alt="post" />
            <div class="post-info">
              <div class="post-profile">
                <div class="post-img">
                  <img src="https://api.dicebear.com/5.x/adventurer/svg?seed=prnnzay" height={100} width={100} alt="profile" />
                </div>
                <h3>Aryan</h3>
              </div>
              <div class="likes">
                <i class="ri-heart-line"></i>
                <span>84.5k</span>
                <i class="ri-chat-3-line"></i>
                <span>104</span>
              </div>
            </div>
          </div>
          <div class="post-box  bg-white p-2 rounded-md">
            <img src="https://api.dicebear.com/5.x/adventurer/svg?seed=prpay" height={100} width={100} alt="post" />
            <div class="post-info">
              <div class="post-profile">
                <div class="post-img">
                  <img src="https://api.dicebear.com/5.x/adventurer/svg?seed=prnnzay" height={100} width={100} alt="profile" />
                </div>
                <h3>Aryan</h3>
              </div>
              <div class="likes">
                <i class="ri-heart-line"></i>
                <span>84.5k</span>
                <i class="ri-chat-3-line"></i>
                <span>104</span>
              </div>
            </div>
          </div>
          <div class="post-box  bg-white p-2 rounded-md">
            <img src="https://api.dicebear.com/5.x/adventurer/svg?seed=prpay" height={100} width={100} alt="post" />
            <div class="post-info">
              <div class="post-profile">
                <div class="post-img">
                  <img src="https://api.dicebear.com/5.x/adventurer/svg?seed=prnnzay" height={100} width={100} alt="profile" />
                </div>
                <h3>Aryan</h3>
              </div>
              <div class="likes">
                <i class="ri-heart-line"></i>
                <span>84.5k</span>
                <i class="ri-chat-3-line"></i>
                <span>104</span>
              </div>
            </div>
          </div>
          <div class="post-box  bg-white p-2 rounded-md">
            <img src="https://api.dicebear.com/5.x/adventurer/svg?seed=prpay" height={100} width={100} alt="post" />
            <div class="post-info">
              <div class="post-profile">
                <div class="post-img">
                  <img src="https://api.dicebear.com/5.x/adventurer/svg?seed=prnnzay" height={100} width={100} alt="profile" />
                </div>
                <h3>Aryan</h3>
              </div>
              <div class="likes">
                <i class="ri-heart-line"></i>
                <span>84.5k</span>
                <i class="ri-chat-3-line"></i>
                <span>104</span>
              </div>
            </div>
          </div>
          <div class="post-box  bg-white p-2 rounded-md">
            <img src="https://api.dicebear.com/5.x/adventurer/svg?seed=prpay" height={100} width={100} alt="post" />
            <div class="post-info">
              <div class="post-profile">
                <div class="post-img">
                  <img src="https://api.dicebear.com/5.x/adventurer/svg?seed=prnnzay" height={100} width={100} alt="profile" />
                </div>
                <h3>Aryan</h3>
              </div>
              <div class="likes">
                <i class="ri-heart-line"></i>
                <span>84.5k</span>
                <i class="ri-chat-3-line"></i>
                <span>104</span>
              </div>
            </div>
          </div>

        </div>

      </div>

      






    </>
  )
}
